# Generated by Django 4.2.1 on 2023-12-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.category')),
            ],
        ),
    ]
